foreach(required UVSR_DXC_EXECUTABLE UVSR_SOURCE_DIRECTORY UVSR_TEST_DIRECTORY
        UVSR_SHADER_CATALOG_DIRECTORY UVSR_GPU_CONTRACT_TEST)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${UVSR_TEST_DIRECTORY}")
file(GLOB catalogs "${UVSR_SHADER_CATALOG_DIRECTORY}/*.txt")
foreach(catalog IN LISTS catalogs)
    file(STRINGS "${catalog}" rows)
    foreach(row IN LISTS rows)
        if(NOT "${row}" MATCHES "^(.*)\t(.+)$")
            message(FATAL_ERROR "Malformed shader catalog ${catalog}")
        endif()
        set(key "${CMAKE_MATCH_1}")
        set(object "${CMAKE_MATCH_2}")
        get_filename_component(name "${object}" NAME)
        string(REGEX REPLACE "\\.[0-9a-f]+\\.dxil$" "" family "${name}")
        string(SHA256 id "${family}|${key}")
        if(DEFINED object_${id})
            message(FATAL_ERROR "Duplicate shader permutation ${family}: ${key}")
        endif()
        set(object_${id} "${object}")
    endforeach()
endforeach()

function(keep_layout name text)
    if("${text}" MATCHES "; Buffer Definitions:")
        set(path "${UVSR_TEST_DIRECTORY}/${name}.dump")
        file(WRITE "${path}" "${text}")
        set_property(GLOBAL APPEND PROPERTY UVSR_ABI_DUMPS "${path}")
    endif()
endfunction()
function(reflect family key)
    string(SHA256 id "${family}|${key}")
    if(NOT DEFINED object_${id})
        message(FATAL_ERROR "Missing required compiled permutation ${family}: ${key}")
    endif()
    execute_process(COMMAND "${UVSR_DXC_EXECUTABLE}" -dumpbin "${object_${id}}"
        OUTPUT_VARIABLE text COMMAND_ERROR_IS_FATAL ANY)
    keep_layout("${id}" "${text}")
    set(dump "${text}" PARENT_SCOPE)
    set(label "${family} [${key}]" PARENT_SCOPE)
endfunction()
function(require)
    math(EXPR last "${ARGC} - 1")
    foreach(index RANGE 0 ${last})
        set(pattern "${ARGV${index}}")
        if(NOT "${dump}" MATCHES "${pattern}")
            message(FATAL_ERROR "${label}: missing ${pattern}")
        endif()
    endforeach()
endfunction()
function(reject pattern)
    if("${dump}" MATCHES "${pattern}")
        message(FATAL_ERROR "${label}: unexpected ${pattern}")
    endif()
endfunction()
function(occurrences pattern expected)
    string(REGEX MATCHALL "${pattern}" matches "${dump}")
    list(LENGTH matches count)
    if(NOT count EQUAL expected)
        message(FATAL_ERROR "${label}: ${pattern} occurs ${count}, expected ${expected}")
    endif()
endfunction()
function(bindings type topology)
    foreach(binding IN LISTS ARGN)
        string(REPLACE "=" ";" pair "${binding}")
        list(GET pair 0 name)
        list(GET pair 1 slot)
        require("${name}[^\r\n]*${type}[^\r\n]*${topology}[^\r\n]*${slot}[ ]+1")
    endforeach()
endfunction()
function(members)
    foreach(item IN LISTS ARGN)
        string(REPLACE "=" ";" pair "${item}")
        list(GET pair 0 name)
        list(GET pair 1 offset)
        require("${name}(\\[[0-9]+\\])?;[^\r\n]*Offset:[ ]*${offset}([\r\n]|$)")
    endforeach()
endfunction()
function(size name bytes)
    require("${name};[^\r\n]*Size:[ ]*${bytes}([\r\n]|$)")
endfunction()
function(threads x y z)
    require("NumThreads=\\(${x},${y},${z}\\)")
endfunction()
function(ray_queries samples)
    foreach(operation rayQuery_TraceRayInline rayQuery_CommitNonOpaqueTriangleHit)
        occurrences("call[^\r\n]*@dx\\.op\\.${operation}" ${samples})
    endforeach()
    math(EXPR proceeds "${samples} * 2")
    occurrences("call[^\r\n]*@dx\\.op\\.rayQuery_Proceed" ${proceeds})
    occurrences("call[ \t]+i32[ \t]+@dx\\.op\\.rayQuery_StateScalar\\.i32\\(i32[ \t]+184," ${samples})
    require("RayQuery_CommittedStatus")
endfunction()
function(ray_resources constants samples)
    bindings(cbuffer "" "${constants}=cb0")
    bindings(sampler "" s_RayMaterialSampler=s0)
    bindings(ras "" t_WorldBvh=t0)
    bindings("" "" t_RayMaterialGeometries=t10 t_RayMaterials=t11 t_RayGeometryIndexMap=t12)
    require("t_RayMaterialBuffers[^\r\n]*t0,space1unbounded"
        "t_RayMaterialTextures[^\r\n]*t0,space2unbounded")
    threads(8 8 1)
    ray_queries(${samples})
endfunction()

# Compare actual C++ layouts with the compiled probe and production permutations.
foreach(kind cs ps)
    if(kind STREQUAL "cs")
        set(entry main)
    else()
        set(entry material_main)
    endif()
    set(probe "${UVSR_TEST_DIRECTORY}/gpu-${kind}.dxil")
    execute_process(COMMAND "${UVSR_DXC_EXECUTABLE}" -nologo -T "${kind}_6_5" -E "${entry}"
        -D TARGET_D3D12 -enable-16bit-types -O3 -WX -I "${UVSR_SOURCE_DIRECTORY}/src"
        -Fo "${probe}" "${UVSR_SOURCE_DIRECTORY}/tests/renderer_gpu_contract_probe.hlsl"
        COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND "${UVSR_DXC_EXECUTABLE}" -dumpbin "${probe}"
        OUTPUT_VARIABLE probe_${kind} COMMAND_ERROR_IS_FATAL ANY)
    keep_layout("gpu-${kind}" "${probe_${kind}}")
endforeach()
set(label "renderer GPU ABI")
set(dump "${probe_cs}")
bindings("" "" c_Probe=cb0 g_Deferred=cb1 g_GBuffer=cb2
    t_Geometry=t8 t_Instance=t9 t_Materials=t10 u_Output=u0)
require("row_major float4x4 matWorldToView" "row_major float3x4 transform")
set(dump "${probe_ps}")
require("POS[ ]+0[ ]+xyz" "PREV_POS[ ]+0[ ]+xyz" "TEXCOORD[ ]+0[ ]+xy"
    "NORMAL[ ]+0[ ]+xyz" "TANGENT[ ]+0[ ]+xyzw"
    "NORMAL[ ]+0[^\r\n]*centroid" "TANGENT[ ]+0[^\r\n]*centroid")

foreach(depth 0 1)
    reflect(renderer_fullscreen_vs "UVSR_FULLSCREEN_DEPTH=${depth}")
    require("SV_VertexID[ ]+0[ ]+x" "SV_Position[ ]+0[ ]+xyzw" "UV[ ]+0[ ]+xy")
    require("storeOutput\\.f32[^\r\n]*i8 2, float ${depth}\\.000000e\\+00")
endforeach()
reflect(renderer_blit_ps "")
require("UV[ ]+0[ ]+xy" "SV_Target[ ]+0[ ]+xyzw")
bindings("" "" s_LinearClamp=s0 t_Source=t0)
reflect(renderer_pixel_readback_cs "")
threads(1 1 1)
bindings(cbuffer "" c_Readback=cb0)
bindings(u32 "2d[ ]" t_Source=t0)
bindings(u32 "buf[ ]" u_Destination=u0)

foreach(shader auto_exposure_histogram_cs auto_exposure_resolve_cs)
    reflect("${shader}" "")
    size(c_AutoExposure 48)
    bindings(cbuffer "" c_AutoExposure=cb0)
    members(viewOrigin=0 viewSize=8 frameDeltaSeconds=16 exposureCompensationEV=20
        adjustmentPeriodSeconds=24 resetExposure=28 maximumBrighteningEV=32 maximumDarkeningEV=36 padding=40)
    if(shader STREQUAL "auto_exposure_histogram_cs")
        bindings(f32 "2d[ ]" t_SceneColor=t0)
        bindings(u32 "buf[ ]" u_Histogram=u0)
        threads(16 16 1)
    else()
        bindings(u32 "buf[ ]" t_Histogram=t0)
        bindings(f32 "buf[ ]" u_Exposure=u0)
        threads(1 1 1)
    endif()
endforeach()
foreach(unity 0 1)
    foreach(lut 0 1)
        reflect(agx_tonemapping_ps "UVSR_UNITY_EXPOSURE=${unity} UVSR_USE_LUT=${lut}")
        bindings(f32 "2d[ ]" t_SceneColor=t0)
        bindings("" "" c_ToneMapping=cb0)
        require("SV_Target[ ]+0[ ]+xyzw")
        if(unity)
            reject("t_AutoExposure")
        else()
            bindings(f32 "buf[ ]" t_AutoExposure=t1)
        endif()
        if(lut)
            bindings(f32 "3d[ ]" t_ColorLut=t2)
            bindings("" "" s_LutSampler=s0)
        else()
            reject("t_ColorLut|s_LutSampler")
        endif()
    endforeach()
endforeach()

reflect(ray_traced_sky_visibility_cs_Generate "")
ray_resources(c_RayTracedSkyVisibility 1)
bindings(f32 "2d[ ]" t_Depth=t1 t_GBufferMaterial=t2 t_GBufferNormals=t3 u_Visibility=u0)
bindings("" "" t_Noise=t4 t_AttemptMask=t5)
reject("u_HitDistance")
reflect(ray_traced_flashlight_shadows_cs_GenerateVisibility "")
ray_resources(c_FlashlightShadows 1)
bindings(f32 "2d[ ]" t_Depth=t1 t_GBufferMaterial=t2 t_GBufferNormals=t3 u_Visibility=u0)
reject("u_HitDistance")
reflect(directional_ray_visibility_cs "")
# one call site serves the exact hard ray, the other serves the soft-sample loop.
ray_resources(c_DirectionalVisibility 2)
bindings(f32 "2d[ ]" t_Depth=t1 t_GBufferMaterial=t2 t_GBufferNormals=t3 u_Visibility=u0)
bindings("" "" t_Noise=t4 t_AttemptMask=t5)

reflect(pbr_deferred_lighting_cs "")
reject("u_SourceRadiance")
bindings(f32 "cubearray[ ]" t_DiffuseEnvironment=t1 t_SpecularEnvironment=t2)
bindings(f32 "2d[ ]" t_EnvironmentBrdf=t3 t_FlashlightVisibility=t20 t_SunVisibility=t21 t_SkyVisibility=t22)
threads(16 16 1)

reflect(path_tracing_cs "")
string(FIND "${dump}" "; Resource Bindings:" start)
string(FIND "${dump}" "target datalayout" end)
if(start LESS 0 OR end LESS_EQUAL start)
    message(FATAL_ERROR "Path tracing has no reflected resource table")
endif()
math(EXPR length "${end} - ${start}")
string(SUBSTRING "${dump}" ${start} ${length} table)
string(REGEX MATCHALL "(cbuffer|sampler|texture|UAV)[ ]+(NA|i32|f32|struct|byte|u32)" resources "${table}")
list(LENGTH resources resource_count)
if(NOT resource_count EQUAL 14)
    message(FATAL_ERROR "Path tracing must expose exactly 14 resources")
endif()
bindings("" "" c_PathTracing=cb0 s_RayMaterialSampler=s0)
bindings(ras "" t_WorldBvh=t0)
bindings(f32 "cube[ ]" t_Environment=t1)
bindings(f32 "2darray[ ]" t_Noise=t2)
bindings(struct "" t_PathTracingLights=t13
    t_RayMaterialGeometries=t10 t_RayMaterials=t11 t_RayGeometryIndexMap=t12)
bindings(f32 "2d[ ]" u_RawMean=u0)
bindings(u32 "2d[ ]" u_SuccessfulSampleCount=u1 u_RetryGeneration=u4)
require("t_RayMaterialBuffers[^\r\n]*t0,space1unbounded"
    "t_RayMaterialTextures[^\r\n]*t0,space2unbounded" "rayQuery_TraceRayInline" "rayQuery_Proceed")
threads(8 8 1)

reflect(fast_approximate_aa_ps "")
size(FastApproximateAaConstants 32)
bindings("" "" FastApproximateAaConstants=cb0 s_LinearClamp=s0 t_DisplayLinear=t0)
require("SV_Position[^\r\n]*float" "UV[^\r\n]*float" "SV_Target[^\r\n]*float"
    "dx\\.op\\.dot3" "dx\\.op\\.unary\\.f32\\(i32 24" "dx\\.op\\.storeOutput\\.f32")

reflect(pixel_zoom_ps "")
require("SV_Position[ ]+0[ ]+xyzw[ ]+0[ ]+POS[ ]+float[ ]+xy"
    "UV[ ]+0[ ]+xy[ ]+1[ ]+NONE[ ]+float"
    "SV_Target[ ]+0[ ]+xyzw[ ]+0[ ]+TARGET[ ]+float[ ]+xyzw")
size(c_PixelZoom 96)
bindings(cbuffer "" c_PixelZoom=cb0)
bindings(texture "2d[ ]" t_Source=t0)
occurrences("call[^\r\n]*@dx\\.op\\.textureLoad\\.f32" 1)
occurrences("call[^\r\n]*@dx\\.op\\.discard" 1)
reject("call[^\r\n]*@dx\\.op\\.sample")
reject("[^\r\n]*sampler[^\r\n]*s[0-9]+[ ]+[0-9]+")
get_property(abi_dumps GLOBAL PROPERTY UVSR_ABI_DUMPS)
execute_process(COMMAND "${UVSR_GPU_CONTRACT_TEST}" ${abi_dumps}
    OUTPUT_FILE "${UVSR_TEST_DIRECTORY}/host-gpu-layout.txt" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Compiled shader ABI, resources, dispatch and retained permutations passed")
