"""Compile the upstream task/mesh fixture for the existing numeric cube oracle."""
import argparse
import json
from pathlib import Path
import re
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shader_build import compiler_inputs, run, sha256
from compile_readback import check_cube_profile

CAPABILITIES = {"Shader", "Int64", "VulkanMemoryModel", "PhysicalStorageBufferAddresses",
                "UntypedPointersKHR", "DescriptorHeapEXT", "MeshShadingEXT"}
EXTENSIONS = {"SPV_EXT_descriptor_heap", "SPV_KHR_untyped_pointers", "SPV_EXT_mesh_shader"}
ENTRIES = [{"stage": stage, "entry_point": stage + "Main"} for stage in ("task", "mesh", "fragment")]


def check_profile(assembly):
    if (set(re.findall(r"OpCapability (\S+)", assembly)) != CAPABILITIES
            or set(re.findall(r'OpExtension "(\S+)"', assembly)) != EXTENSIONS
            or "OpMemoryModel PhysicalStorageBuffer64 Vulkan" not in assembly
            or re.search(r"\b(DescriptorSet|Binding|Restrict|RestrictPointer|VertexIndex)\b", assembly)
            or len(re.findall(r"OpExecutionMode %\S+ LocalSize 1 1 1", assembly)) != 2):
        raise ValueError("unexpected task/mesh shader profile")
    check_cube_profile(assembly, mesh=True)
    constants = {name: int(value) for name, value in re.findall(r"(%\S+) = OpConstant %\S+ (\d+)\s*$", assembly, re.M)}
    for opcode, values in (("OpEmitMeshTasksEXT", [6, 1, 1]), ("OpSetMeshOutputsEXT", [4, 2])):
        operands = re.findall(opcode + r" ([^\r\n]+)", assembly)
        if len(operands) != 1 or [constants.get(word) for word in operands[0].split()[:len(values)]] != values:
            raise ValueError("unexpected mesh workgroup or output counts")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("upstream", "backend", "output-dir"):
        parser.add_argument("--" + name, required=True, type=Path)
    args = parser.parse_args()
    upstream, backend, output = args.upstream.resolve(), args.backend.resolve(), args.output_dir.resolve()
    source = upstream / "tests/compiletests/ui/descriptor_heap/auxiliary/mesh_body.rs"
    output.mkdir(parents=True, exist_ok=True)
    header_path = output / "native_heap_mesh_modules.hpp"
    header_path.unlink(missing_ok=True)
    common, identity, validator, disassembler = compiler_inputs(upstream, backend, source, "spirv-unknown-vulkan1.3-physical64")
    common += ["-Zcrate-attr=no_std", "-Zcrate-attr=deny(unsafe_code)", "-Zcrate-attr=deny(unsafe_op_in_unsafe_fn)",
               "-Ctarget-feature=+UntypedPointersKHR,+DescriptorHeapEXT,+MeshShadingEXT,+ext:SPV_KHR_untyped_pointers,+ext:SPV_EXT_descriptor_heap,+ext:SPV_EXT_mesh_shader"]
    header = ["// Generated by compile_native_heap_mesh.py. Do not track.", "#pragma once", ""]
    for qptr in (False, True):
        for level in (0, 3):
            variant = ("qptr" if qptr else "default") + f"_opt{level}"
            stem = "native_heap_mesh_" + variant
            module = output / (stem + ".spv")
            command = common + [f"-Copt-level={level}"]
            if qptr:
                command += ["-Cllvm-args=--spirt-passes=qptr"]
            command += ["-o", str(module) + ".json"]
            run(command, upstream, output / (stem + "_rustc"))
            if sorted(json.loads(Path(str(module) + ".json").read_text())["entry_points"]) != ["fragmentMain", "meshMain", "taskMain"]:
                raise ValueError("unexpected task/mesh entry points")
            run([validator, "--target-env", "vulkan1.3", str(module)], upstream, output / (stem + "_validate"))
            assembly = run([disassembler, str(module)], upstream, output / (stem + "_disassemble"))
            (output / (stem + ".spvasm")).write_text(assembly, encoding="utf-8")
            check_profile(assembly)
            record = dict(schema_version=1, case_id="theta.m2.ngapi.native_heap_mesh.compile." + variant,
                          status="pass", language="Rust", entry_points=ENTRIES, root_bytes=80, task_payload_bytes=80,
                          vertex_count=24, vertex_stride=24, primitive_count=12, workgroup_size=[1, 1, 1],
                          task_group_count=[1, 1, 1], mesh_group_count=[6, 1, 1], mesh_output_vertices=4, mesh_output_primitives=2,
                          variant=variant, optimization_level=level, spirt_passes=["qptr"] if qptr else [],
                          target="spirv-unknown-vulkan1.3-physical64", profile="ngapi-native-heap-mesh", payload_type="SPIR-V",
                          payload_sha256=sha256(module), capabilities=sorted(CAPABILITIES), extensions=sorted(EXTENSIONS),
                          identity=identity, rustc_command=command)
            (output / (stem + ".metadata.json")).write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
            words = struct.unpack(f"<{module.stat().st_size // 4}I", module.read_bytes())
            header += [f'static const char {stem}_sha256[] = "{sha256(module)}";', f"static const gpu::uint32 {stem}[] = {{"]
            header += ["    " + ", ".join(f"0x{word:08x}" for word in words[i:i+8]) + "," for i in range(0, len(words), 8)]
            header += ["};", ""]
            print(json.dumps({"variant": variant, "status": "pass", "payload_sha256": record["payload_sha256"]}))
    for label, digest in (("source", identity["source_sha256"]),
                          ("host", sha256(Path(__file__).with_name("native_heap_cube.cpp"))),
                          ("abi", sha256(Path(__file__).with_name("native_heap_cube.hpp")))):
        header += [f'static const char native_heap_mesh_{label}_sha256[] = "{digest}";']
    header_path.write_text("\n".join(header) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
