"""Compile the bounded NGAPI consumer with the prepared physical64 test sysroot.

Run the prerequisite RustGPU physical_storage compiletests first. This diagnostic
uses their exact ABI-specific libraries, not the native host sysroot. Generated
SPIR-V, C++ includes, metadata and logs belong in an ignored output directory.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import struct
import subprocess


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def one(paths, description):
    paths = list(paths)
    if len(paths) != 1:
        raise RuntimeError(f"expected one {description}, found {len(paths)}")
    return paths[0].resolve()


def run(command, directory, prefix):
    result = subprocess.run(command, cwd=directory, capture_output=True, timeout=180)
    prefix.with_suffix(".stdout.txt").write_bytes(result.stdout)
    prefix.with_suffix(".stderr.txt").write_bytes(result.stderr)
    if result.returncode:
        raise RuntimeError(f"{command[0]} failed with {result.returncode}: see {prefix}.stderr.txt")
    return result.stdout.decode("utf-8").replace("\r\n", "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rustgpu-source", type=Path, required=True)
    parser.add_argument("--codegen-backend", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    upstream = args.rustgpu_source.resolve()
    backend = args.codegen_backend.resolve(strict=True)
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    # A failed rebuild must not leave a compilable include from an older source.
    (output / "physical_readback_modules.hpp").unlink(missing_ok=True)
    source = Path(__file__).with_name("physical_readback.rs").resolve()
    target = upstream / "target/compiletest-target-spec/spirv-unknown-vulkan1.3-physical64.json"
    deps = upstream / "target/compiletest-deps"
    shader_build = deps / "spirv-unknown-vulkan1.3-physical64/debug/build"
    host_build = deps / "debug/build"
    libraries = {}
    for name in ["compiler_builtins", "core", "spirv-std", "glam"]:
        ident = name.replace("-", "_")
        libraries[ident] = one((shader_build / name).glob(f"*/out/lib{ident}*.rlib"), name)
    libraries["spirv_std_macros"] = one(
        (host_build / "spirv-std-macros").glob("*/out/spirv_std_macros*.dll"), "Windows spirv-std-macros"
    )
    search_paths = sorted({path.resolve() for build in [shader_build, host_build] for path in build.glob("*/*/out")})
    rustc = shutil.which("rustc")
    validator = shutil.which("spirv-val")
    disassembler = shutil.which("spirv-dis")
    if not all([rustc, validator, disassembler]):
        raise RuntimeError("rustc, spirv-val and spirv-dis must be available in the owned tool environment")
    identity = {
        "source_sha256": sha256(source),
        "rustc": subprocess.check_output([rustc, "-vV"], text=True).strip(),
        "rustgpu_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=upstream, text=True).strip(),
        "codegen_backend_sha256": sha256(backend),
        "target_sha256": sha256(target),
        "libraries": {name: {"path": str(path), "sha256": sha256(path)} for name, path in libraries.items()},
        "validator_sha256": sha256(Path(validator)),
        "validator_version": subprocess.check_output([validator, "--version"], text=True).strip(),
    }
    common = [
        rustc, str(source), "--edition=2021", "--crate-type=dylib", "--crate-name=physical_readback",
        "--target", str(target), "-Zunstable-options",
        f"-Zcodegen-backend={backend}", "-Zbinary-dep-depinfo", "-Csymbol-mangling-version=v0",
        "-Zcrate-attr=feature(register_tool)", "-Zcrate-attr=register_tool(rust_gpu)",
        "-Zcrate-attr=feature(asm_experimental_arch)", "-Coverflow-checks=off", "-Cdebug-assertions=off",
        "-Zinline-mir=off", "-Zmir-enable-passes=-GVN", "-Zshare-generics=off",
        "-Cembed-bitcode=no", "-Cdebuginfo=0", "-Clto=off",
    ]
    for path in search_paths:
        common += ["-L", f"dependency={path}"]
    for name, path in libraries.items():
        prefix = "noprelude:" if name in {"core", "compiler_builtins"} else ""
        common += ["--extern", f"{prefix}{name}={path}"]
    header = ["// Generated by compile_readback.py. Do not edit or track.", "#pragma once", ""]
    for level in [0, 3]:
        stem = f"physical_readback_opt{level}"
        module = output / f"{stem}.spv"
        command = common + [f"-Copt-level={level}", "-o", str(module) + ".json"]
        run(command, upstream, output / f"{stem}_rustc")
        result = json.loads(Path(str(module) + ".json").read_text())
        if result["entry_points"] != ["computeMain"]:
            raise RuntimeError(f"unexpected entry points: {result['entry_points']}")
        run([validator, "--target-env", "vulkan1.3", str(module)], upstream, output / f"{stem}_validate")
        assembly = run([disassembler, str(module)], upstream, output / f"{stem}_disassemble")
        (output / f"{stem}.spvasm").write_text(assembly, encoding="utf-8")
        capabilities = [line.split("OpCapability ", 1)[1].strip() for line in assembly.splitlines() if "OpCapability " in line]
        extensions = [line.split("OpExtension ", 1)[1].strip().strip('"') for line in assembly.splitlines() if "OpExtension " in line]
        if set(capabilities) != {"Shader", "Int64", "VulkanMemoryModel", "PhysicalStorageBufferAddresses"} or extensions:
            raise RuntimeError("module feature requirements changed. Review the NGAPI feature patch before dispatch")
        if ("OpMemoryModel PhysicalStorageBuffer64 Vulkan" not in assembly
                or not re.search(r'OpEntryPoint GLCompute %\S+ "computeMain"', assembly)
                or not re.search(r"OpExecutionMode %\S+ LocalSize 1 1 1", assembly)
                or re.search(r"\b(DescriptorSet|Binding|Uniform|StorageBuffer)\b", assembly)
                or len(re.findall(r"OpLoad .* Aligned 4", assembly)) != 1
                or len(re.findall(r"OpStore .* Aligned 4", assembly)) != 3):
            raise RuntimeError("module no longer matches the reviewed scalar physical-readback profile")
        root_type = re.search(r"(%\S+) = OpTypeStruct (%\S+) \2", assembly)
        if (not root_type or not re.search(re.escape(root_type[2]) + r" = OpTypeInt 64 0", assembly)
                or f"OpMemberDecorate {root_type[1]} 0 Offset 0" not in assembly
                or f"OpMemberDecorate {root_type[1]} 1 Offset 8" not in assembly):
            raise RuntimeError("root data no longer has the reviewed two-u64 layout")
        record = {
            "schema_version": 1, "case_id": f"theta.m2.ngapi.physical_readback.compile.opt{level}",
            "status": "pass", "language": "Rust", "stage": "compute", "entry_point": "computeMain",
            "workgroup_size": [1, 1, 1], "target": "spirv-unknown-vulkan1.3-physical64",
            "profile": "ngapi-physical-readback", "payload_type": "SPIR-V", "payload_sha256": sha256(module),
            "capabilities": capabilities, "extensions": extensions, "root_bytes": 16,
            "rustc_command": command, "identity": identity,
        }
        (output / f"{stem}.metadata.json").write_text(json.dumps(record, indent=2) + "\n")
        words = struct.unpack(f"<{module.stat().st_size // 4}I", module.read_bytes())
        header += [f'static const char {stem}_sha256[] = "{sha256(module)}";', f"static const gpu::uint32 {stem}[] = {{"]
        for start in range(0, len(words), 8):
            header += ["    " + ", ".join(f"0x{word:08x}" for word in words[start:start + 8]) + ","]
        header += ["};", ""]
        print(json.dumps({key: record[key] for key in ["case_id", "status", "payload_sha256", "capabilities"]}))
    header += [f'static const char physical_readback_source_sha256[] = "{identity["source_sha256"]}";', ""]
    (output / "physical_readback_modules.hpp").write_text("\n".join(header), encoding="utf-8")


if __name__ == "__main__":
    main()
