"""Compile the single upstream aggregate/alias fixture for the actual NGAPI host."""
import argparse
import json
from pathlib import Path
import re
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shader_build import compiler_inputs, run, sha256


def check_profile(assembly):
    capabilities = re.findall(r"OpCapability (\S+)", assembly)
    if set(capabilities) != {"Shader", "Int64", "VulkanMemoryModel", "PhysicalStorageBufferAddresses"}:
        raise ValueError("unexpected physical operations capabilities")
    if ("OpMemoryModel PhysicalStorageBuffer64 Vulkan" not in assembly
            or re.search(r"\b(DescriptorSet|Binding|Uniform|StorageBuffer|Restrict|RestrictPointer)\b", assembly)
            or "OpExtension" in assembly):
        raise ValueError("unexpected physical operations addressing or alias profile")
    required = [r'OpEntryPoint GLCompute %\S+ "computeMain"',
                r"OpExecutionMode %\S+ LocalSize 1 1 1", r"OpLoad .* Aligned 8",
                r"OpStore .* Aligned 4", r"OpMemberDecorate %\S+ 2 Offset 20"]
    if any(not re.search(pattern, assembly) for pattern in required):
        raise ValueError("missing reviewed entry, aggregate layout or physical access")
    if (len(re.findall(r"OpLoad .* Volatile", assembly)) != 2
            or len(re.findall(r"OpStore .* Volatile", assembly)) != 1):
        raise ValueError("volatile Function accesses were lost or changed")
    return capabilities


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream", required=True, type=Path)
    parser.add_argument("--backend", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    upstream, backend, output = args.upstream.resolve(), args.backend.resolve(), args.output_dir.resolve()
    source = upstream / "tests/compiletests/ui/physical_storage/auxiliary/operations_body.rs"
    output.mkdir(parents=True, exist_ok=True)
    header_path = output / "physical_operations_modules.hpp"
    header_path.unlink(missing_ok=True)
    common, identity, validator, disassembler = compiler_inputs(upstream, backend, source, "spirv-unknown-vulkan1.3-physical64")
    common += ["-Zcrate-attr=no_std", "-Zcrate-attr=deny(unsafe_code)", "-Zcrate-attr=deny(unsafe_op_in_unsafe_fn)"]
    header = ["// Generated by compile_physical_operations.py. Do not track.", "#pragma once", ""]
    for qptr in (False, True):
        for level in (0, 3):
            variant = ("qptr" if qptr else "default") + f"_opt{level}"
            stem = "physical_operations_" + variant
            module = output / f"{stem}.spv"
            command = common + [f"-Copt-level={level}"]
            if qptr:
                command += ["-Cllvm-args=--spirt-passes=qptr"]
            command += ["-o", str(module) + ".json"]
            run(command, upstream, output / f"{stem}_rustc")
            entries = json.loads(Path(str(module) + ".json").read_text())["entry_points"]
            if sorted(entries) != ["computeMain"]:
                raise ValueError("unexpected shader entry points")
            run([validator, "--target-env", "vulkan1.3", str(module)], upstream, output / f"{stem}_validate")
            assembly = run([disassembler, str(module)], upstream, output / f"{stem}_disassemble")
            (output / f"{stem}.spvasm").write_text(assembly, encoding="utf-8")
            capabilities = check_profile(assembly)
            record = {"schema_version": 1, "case_id": "theta.m2.ngapi.physical_operations.compile." + variant,
                      "status": "pass", "language": "Rust", "stage": "compute", "entry_point": "computeMain",
                      "root_bytes": 16, "source_bytes": 24, "allocation_bytes": 32, "workgroup_size": [1, 1, 1],
                      "variant": variant, "optimization_level": level, "spirt_passes": ["qptr"] if qptr else [],
                      "target": "spirv-unknown-vulkan1.3-physical64", "profile": "ngapi-physical-operations",
                      "payload_type": "SPIR-V", "payload_sha256": sha256(module), "capabilities": capabilities,
                      "extensions": [], "identity": identity, "rustc_command": command}
            (output / f"{stem}.metadata.json").write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
            words = struct.unpack(f"<{module.stat().st_size // 4}I", module.read_bytes())
            header += [f'static const char {stem}_sha256[] = "{sha256(module)}";', f"static const gpu::uint32 {stem}[] = {{"]
            header += ["    " + ", ".join(f"0x{word:08x}" for word in words[i:i+8]) + "," for i in range(0, len(words), 8)]
            header += ["};", ""]
            print(json.dumps({"variant": variant, "status": "pass", "payload_sha256": record["payload_sha256"]}))
    host = Path(__file__).with_name("physical_operations.cpp")
    root_header = Path(__file__).with_name("physical_readback.hpp")
    header += [f'static const char physical_operations_source_sha256[] = "{identity["source_sha256"]}";',
               f'static const char physical_operations_host_sha256[] = "{sha256(host)}";',
               f'static const char physical_operations_root_sha256[] = "{sha256(root_header)}";', ""]
    header_path.write_text("\n".join(header), encoding="utf-8")


if __name__ == "__main__":
    main()
