"""Compile the shared upstream storage-image fixture for actual NGAPI."""
import argparse
import json
from pathlib import Path
import re
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shader_build import compiler_inputs, run, sha256

CAPABILITIES = {"Shader", "Int64", "VulkanMemoryModel", "PhysicalStorageBufferAddresses",
                "UntypedPointersKHR", "DescriptorHeapEXT", "ShaderNonUniform", "StorageImageArrayNonUniformIndexing"}
EXTENSIONS = {"SPV_EXT_descriptor_heap", "SPV_KHR_untyped_pointers"}


def check_profile(assembly):
    capabilities = re.findall(r"OpCapability (\S+)", assembly)
    if set(capabilities) != CAPABILITIES or set(re.findall(r'OpExtension "(\S+)"', assembly)) != EXTENSIONS:
        raise ValueError("unexpected storage-image capabilities or extensions")
    if re.search(r"\b(DescriptorSet|Binding|SamplerHeapEXT|Restrict|RestrictPointer)\b", assembly):
        raise ValueError("unexpected descriptor/alias interface")
    required = [r"OpMemoryModel PhysicalStorageBuffer64 Vulkan", r'OpEntryPoint GLCompute %\S+ "computeMain"',
                r"OpExecutionMode %\S+ LocalSize 1 1 1", r"OpTypeImage %\S+ 2D 2 0 0 2 Rgba32ui",
                r"BuiltIn ResourceHeapEXT", r"ArrayStrideIdEXT", r"OpConstantSizeOfEXT", r"OpUntypedAccessChainKHR",
                r"OpImageRead", r"OpImageWrite", r"OpStore .* Aligned 4", r"OpMemberDecorate %\S+ 2 Offset 12"]
    if any(not re.search(pattern, assembly) for pattern in required):
        raise ValueError("missing reviewed storage image, native heap, root or physical output")
    return capabilities


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("upstream", "backend", "output-dir"):
        parser.add_argument("--" + name, required=True, type=Path)
    args = parser.parse_args()
    upstream, backend, output = args.upstream.resolve(), args.backend.resolve(), args.output_dir.resolve()
    source = upstream / "tests/compiletests/ui/descriptor_heap/auxiliary/storage_body.rs"
    output.mkdir(parents=True, exist_ok=True)
    header_path = output / "native_heap_storage_modules.hpp"
    header_path.unlink(missing_ok=True)
    common, identity, validator, disassembler = compiler_inputs(upstream, backend, source, "spirv-unknown-vulkan1.3-physical64")
    common += ["-Zcrate-attr=no_std", "-Zcrate-attr=deny(unsafe_code)", "-Zcrate-attr=deny(unsafe_op_in_unsafe_fn)",
               "-Ctarget-feature=+UntypedPointersKHR,+DescriptorHeapEXT,+ShaderNonUniform,+StorageImageArrayNonUniformIndexing,+ext:SPV_KHR_untyped_pointers,+ext:SPV_EXT_descriptor_heap"]
    header = ["// Generated by compile_native_heap_storage.py. Do not track.", "#pragma once", ""]
    for qptr in (False, True):
        for level in (0, 3):
            variant = ("qptr" if qptr else "default") + f"_opt{level}"
            stem = "native_heap_storage_" + variant
            module = output / (stem + ".spv")
            command = common + [f"-Copt-level={level}"]
            if qptr:
                command += ["-Cllvm-args=--spirt-passes=qptr"]
            command += ["-o", str(module) + ".json"]
            run(command, upstream, output / (stem + "_rustc"))
            if sorted(json.loads(Path(str(module) + ".json").read_text())["entry_points"]) != ["computeMain"]:
                raise ValueError("unexpected storage-image entry points")
            run([validator, "--target-env", "vulkan1.3", str(module)], upstream, output / (stem + "_validate"))
            assembly = run([disassembler, str(module)], upstream, output / (stem + "_disassemble"))
            (output / (stem + ".spvasm")).write_text(assembly, encoding="utf-8")
            capabilities = check_profile(assembly)
            record = dict(schema_version=1, case_id="theta.m2.ngapi.native_heap_storage.compile." + variant,
                          status="pass", language="Rust", stage="compute", entry_point="computeMain", root_bytes=16,
                          output_bytes=32, texture_extent=[2, 2], texture_format="rgba32_uint", workgroup_size=[1, 1, 1],
                          variant=variant, optimization_level=level, spirt_passes=["qptr"] if qptr else [],
                          target="spirv-unknown-vulkan1.3-physical64", profile="ngapi-native-heap-storage", payload_type="SPIR-V",
                          payload_sha256=sha256(module), capabilities=capabilities, extensions=sorted(EXTENSIONS),
                          identity=identity, rustc_command=command)
            (output / (stem + ".metadata.json")).write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
            words = struct.unpack(f"<{module.stat().st_size // 4}I", module.read_bytes())
            header += [f'static const char {stem}_sha256[] = "{sha256(module)}";', f"static const gpu::uint32 {stem}[] = {{"]
            header += ["    " + ", ".join(f"0x{word:08x}" for word in words[i:i+8]) + "," for i in range(0, len(words), 8)]
            header += ["};", ""]
            print(json.dumps({"variant": variant, "status": "pass", "payload_sha256": record["payload_sha256"]}))
    header += [f'static const char native_heap_storage_source_sha256[] = "{identity["source_sha256"]}";',
               f'static const char native_heap_storage_host_sha256[] = "{sha256(Path(__file__).with_name("native_heap_storage.cpp"))}";', ""]
    header_path.write_text("\n".join(header), encoding="utf-8")


if __name__ == "__main__":
    main()
