cmake_minimum_required(VERSION 3.24)

set(root "${UVSR_TEST_ROOT}")
if (NOT IS_ABSOLUTE "${root}")
    message(FATAL_ERROR "Dependency test root must be absolute")
endif()
cmake_path(NORMAL_PATH root)
cmake_path(GET root FILENAME name)
if (NOT name MATCHES "^direct-dependency-state-self-test(-[A-Za-z0-9_.-]+)?$")
    message(FATAL_ERROR "Unexpected dependency test root: ${root}")
endif()
if (EXISTS "${root}")
    file(REAL_PATH "${root}" resolved)
    if (IS_SYMLINK "${root}" OR NOT root STREQUAL resolved)
        message(FATAL_ERROR "Redirected dependency test root")
    endif()
endif()
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}/tree/nested" "${root}/git")
set(GIT_EXECUTABLE "${UVSR_GIT_EXECUTABLE}")
file(WRITE "${root}/tree/a.txt" "first\n")
file(WRITE "${root}/tree/nested/b.dxil.h" "second\n")
file(SHA256 "${root}/tree/a.txt" first_hash)
file(SHA256 "${root}/tree/nested/b.dxil.h" second_hash)
string(SHA256 tree_hash "a.txt|${first_hash}\nnested/b.dxil.h|${second_hash}\n")
string(SHA256 header_hash "nested/b.dxil.h|${second_hash}\n")
set(record "${root}/tree/a.txt|${first_hash}")
file(WRITE "${root}/git/tracked.txt" "tracked\n")
execute_process(COMMAND "${GIT_EXECUTABLE}" init --quiet "${root}/git"
    COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${root}/git" add tracked.txt
    COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${root}/git"
    -c user.name=UVSR -c user.email=uvsr@example.invalid commit --quiet -m fixture
    COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${root}/git" rev-parse HEAD
    OUTPUT_VARIABLE head OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)

function(check name expected_error body)
    file(WRITE "${root}/case.cmake"
        "cmake_minimum_required(VERSION 3.24)\n"
        "include([==[${UVSR_VERIFIER}]==])\n"
        "set(GIT_EXECUTABLE [==[${GIT_EXECUTABLE}]==])\n${body}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${root}/case.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if (expected_error STREQUAL "")
        if (NOT result EQUAL 0)
            message(FATAL_ERROR "${name} rejected a valid input: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected_error}")
        message(FATAL_ERROR "${name} did not reject the intended failure: ${output}${error}")
    endif()
endfunction()

set(tree_call "uvsr_verify_dependency_tree([==[${root}/tree]==] 2 ${tree_hash})")
set(header_call "uvsr_verify_dependency_tree([==[${root}/tree]==] 1 ${header_hash} *.dxil.h)")
set(record_call "uvsr_verify_dependency_records([==[${record}]==] 1)")
set(git_call "uvsr_verify_dependency_git([==[${root}/git]==] ${head})")
check(valid "" "${tree_call}\n${header_call}\n${record_call}\n${git_call}")
check(size "size mismatch" "uvsr_verify_dependency_file([==[${root}/tree/a.txt]==] ${first_hash} 99)")
check(missing "not a regular file" "uvsr_verify_dependency_file([==[${root}/missing]==] ${first_hash})")
check(directory "not a regular file" "uvsr_verify_dependency_file([==[${root}/tree]==] ${first_hash})")
check(hash "Malformed dependency SHA-256" "uvsr_verify_dependency_file([==[${root}/tree/a.txt]==] xyz)")
check(relative "must be absolute" "uvsr_verify_dependency_file(tree/a.txt ${first_hash})")
check(record-count "record count mismatch" "uvsr_verify_dependency_records([==[${record}]==] 2)")
check(record-shape "Malformed dependency record" "uvsr_verify_dependency_records([==[${record}|extra]==] 1)")
check(record-duplicate "Duplicate dependency path" "uvsr_verify_dependency_records([==[${record};${record}]==] 2)")
file(APPEND "${root}/tree/a.txt" "tampered")
check(tree-tamper "tree digest mismatch" "${tree_call}")
check(record-tamper "SHA-256 mismatch" "${record_call}")
file(WRITE "${root}/tree/a.txt" "first\n")
file(WRITE "${root}/tree/extra.txt" "extra")
check(tree-count "tree count mismatch" "${tree_call}")
check(header-view "" "${header_call}")
file(REMOVE "${root}/tree/extra.txt")
file(APPEND "${root}/tree/nested/b.dxil.h" "tampered")
check(header-tamper "tree digest mismatch" "${header_call}")
file(WRITE "${root}/tree/nested/b.dxil.h" "second\n")
file(WRITE "${root}/tree/extra.dxil.h" "extra")
check(header-count "tree count mismatch" "${header_call}")
file(REMOVE "${root}/tree/extra.dxil.h")
file(APPEND "${root}/git/tracked.txt" "dirty")
check(git-dirty "not clean" "${git_call}")
file(WRITE "${root}/git/tracked.txt" "tracked\n")
file(WRITE "${root}/git/untracked.txt" "untracked")
check(git-untracked "not clean" "${git_call}")
file(REMOVE "${root}/git/untracked.txt")
check(git-revision "identity mismatch"
    "uvsr_verify_dependency_git([==[${root}/git]==] 0000000000000000000000000000000000000001)")
file(MAKE_DIRECTORY "${root}/git/nested")
check(git-root "identity mismatch"
    "uvsr_verify_dependency_git([==[${root}/git/nested]==] ${head})")
check(final "" "${tree_call}\n${header_call}\n${record_call}\n${git_call}")
message(STATUS "Dependency file, tree, generated header, and Git acceptance passed")
