#define VISIBILITY_ESTIMATOR 1
#define ENABLE_AO 1
#define ENABLE_GI 0
#define ENABLE_BOUNCE_REINJECTION 0
#define INITIALIZE_BOUNCE_CUMULATIVE 0
#define ENABLE_BOUNCE_METADATA 0
#define ENABLE_ADAPTIVE_SPARSE_SAMPLING 0
#define FIXED_SAMPLE_COUNT 8
#include "screen_space_visibility_cs.hlsl"
