#ifndef VISIBILITY_ALGORITHM
#define VISIBILITY_ALGORITHM 1
#endif

#define VISIBILITY_ESTIMATOR 1
#define ENABLE_AO 1
#define ENABLE_GI 0
#define ENABLE_BOUNCE_REINJECTION 0
#define INITIALIZE_BOUNCE_CUMULATIVE 0
#define ENABLE_BOUNCE_METADATA 0
#define ENABLE_ADAPTIVE_SPARSE_SAMPLING 0
#define FIXED_SAMPLE_COUNT 8
#if VISIBILITY_ALGORITHM == 3
// The reference-like Activision candidate uses the published eight total
// horizon samples (four on each side) and its own source-derived spacing,
// falloff, and projected-radius guard below.
#define ACTIVISION_GTAO_REFERENCE 1
#define ACTIVISION_PREPARED_DEPTH 1
#define MAX_PROJECTED_RADIUS_PIXELS 64
#else
#define FIXED_RADIAL_EXPONENT_TWO 1
#endif
#ifndef FIXED_DIRECT_DEPTH
#define FIXED_DIRECT_DEPTH 1
#endif

#if VISIBILITY_ALGORITHM == 1
#define ACTIVISION_SCHEDULE 1
#elif VISIBILITY_ALGORITHM == 2
#define HORIZON_GTAO_CONTROL 1
#elif VISIBILITY_ALGORITHM == 3
#define HORIZON_GTAO_CONTROL 1
#define ACTIVISION_SCHEDULE 1
#elif VISIBILITY_ALGORITHM == 4
#define OUTPUT_PACKED_EDGES 1
#define PACKED_EDGE_MODE 1
#elif VISIBILITY_ALGORITHM == 5
#define OUTPUT_PACKED_EDGES 1
#define PACKED_EDGE_MODE 2
#elif VISIBILITY_ALGORITHM == 6
#define OUTPUT_PACKED_EDGES 1
#define PACKED_EDGE_MODE 3
#elif VISIBILITY_ALGORITHM == 7
#define VISIBILITY_GROUP_SIZE_X 16
#define VISIBILITY_GROUP_SIZE_Y 8
#elif VISIBILITY_ALGORITHM == 8
#define VISIBILITY_GROUP_SIZE_X 8
#define VISIBILITY_GROUP_SIZE_Y 16
#endif

#include "screen_space_visibility_cs.hlsl"
