#define VISIBILITY_ESTIMATOR 1
#define ENABLE_BOUNCE_REINJECTION 0
#define INITIALIZE_BOUNCE_CUMULATIVE 0
#ifndef ENABLE_BOUNCE_METADATA
#define ENABLE_BOUNCE_METADATA 0
#endif
#define FIXED_SAMPLE_COUNT 8
#define FIXED_RADIAL_EXPONENT_TWO 1
#ifndef FIXED_DIRECT_DEPTH
#define FIXED_DIRECT_DEPTH 1
#endif
#define PACKED_FAST_NOISE 1
#define SCHEDULER_SPECIALIZATION 3
#define OUTPUT_PACKED_EDGES 1
#include "screen_space_visibility_cs.hlsl"
