#define VISIBILITY_ESTIMATOR 1
#define ENABLE_AO 1
#define ENABLE_GI 0
#define ENABLE_BOUNCE_REINJECTION 0
#define INITIALIZE_BOUNCE_CUMULATIVE 0
#define ENABLE_BOUNCE_METADATA 0
#define ENABLE_ADAPTIVE_SPARSE_SAMPLING 0
#define FIXED_SAMPLE_COUNT 8
#define FIXED_RADIAL_EXPONENT_TWO 1
#ifndef FIXED_DIRECT_DEPTH
#define FIXED_DIRECT_DEPTH 1
#endif
#ifndef SCHEDULER_SPECIALIZATION
#define SCHEDULER_SPECIALIZATION 2
#endif
#define MAX_PROJECTED_RADIUS_PIXELS 128
#include "screen_space_visibility_cs.hlsl"
