include_guard(GLOBAL)

function(uvsr_disable_cpp_exceptions target)
    set(visibility PUBLIC)
    if(ARGC GREATER 1)
        if(NOT ARGV1 STREQUAL "PRIVATE")
            message(FATAL_ERROR "unsupported exception definition visibility: ${ARGV1}")
        endif()
        set(visibility PRIVATE)
    endif()
    target_compile_definitions(${target} ${visibility} _HAS_EXCEPTIONS=0)
    if(MSVC)
        get_target_property(options ${target} COMPILE_OPTIONS)
        if(options)
            list(FILTER options EXCLUDE REGEX "^/EH")
            set_property(TARGET ${target} PROPERTY COMPILE_OPTIONS "${options}")
        endif()
        target_compile_options(${target} PRIVATE /EHs-c-
            "/FI${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RequireNoCppExceptions.h")
    else()
        target_compile_options(${target} PRIVATE -fno-exceptions
            -include "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RequireNoCppExceptions.h")
    endif()
endfunction()
