include("${CMAKE_CURRENT_LIST_DIR}/RuntimeInventory.cmake")

foreach(name UVSR_RUNTIME_SHADER_INVENTORY UVSR_FRAMEWORK_SHADER_SOURCE_ROOT
        UVSR_APP_SHADER_SOURCE_ROOT UVSR_RUNTIME_SHADER_ALLOWED_PARENT UVSR_RUNTIME_SHADER_ROOT)
    if (NOT DEFINED ${name} OR "${${name}}" STREQUAL "")
        message(FATAL_ERROR "Runtime shader synchronization omits ${name}")
    endif()
endforeach()
foreach(name UVSR_FRAMEWORK_SHADER_SOURCE_ROOT UVSR_APP_SHADER_SOURCE_ROOT
        UVSR_RUNTIME_SHADER_ALLOWED_PARENT UVSR_RUNTIME_SHADER_ROOT)
    if (NOT IS_ABSOLUTE "${${name}}")
        message(FATAL_ERROR "Runtime shader paths must be absolute: ${${name}}")
    endif()
    file(TO_CMAKE_PATH "${${name}}" ${name})
    cmake_path(NORMAL_PATH ${name})
endforeach()

function(uvsr_shader_path_key path output)
    if (WIN32)
        string(TOLOWER "${path}" path)
    endif()
    set(${output} "${path}" PARENT_SCOPE)
endfunction()

# Check the nearest existing ancestor before creating or deleting anything.
function(uvsr_require_unredirected_shader_path path)
    while (NOT EXISTS "${path}" AND NOT IS_SYMLINK "${path}")
        get_filename_component(parent "${path}" DIRECTORY)
        if (parent STREQUAL path)
            message(FATAL_ERROR "No existing shader path ancestor: ${path}")
        endif()
        set(path "${parent}")
    endwhile()
    file(REAL_PATH "${path}" resolved)
    uvsr_shader_path_key("${path}" expected)
    uvsr_shader_path_key("${resolved}" actual)
    if (IS_SYMLINK "${path}" OR NOT expected STREQUAL actual)
        message(FATAL_ERROR "Refusing a redirected shader path: ${path}")
    endif()
endfunction()

uvsr_shader_path_key("${UVSR_RUNTIME_SHADER_ALLOWED_PARENT}/shaders" expected_root)
uvsr_shader_path_key("${UVSR_RUNTIME_SHADER_ROOT}" actual_root)
if (NOT actual_root STREQUAL expected_root)
    message(FATAL_ERROR "Refusing an unexpected runtime shader root: ${UVSR_RUNTIME_SHADER_ROOT}")
endif()
foreach(root "${UVSR_RUNTIME_SHADER_ALLOWED_PARENT}"
        "${UVSR_FRAMEWORK_SHADER_SOURCE_ROOT}" "${UVSR_APP_SHADER_SOURCE_ROOT}")
    if (NOT IS_DIRECTORY "${root}")
        message(FATAL_ERROR "Shader source or parent is not a directory: ${root}")
    endif()
    uvsr_require_unredirected_shader_path("${root}")
endforeach()
uvsr_require_unredirected_shader_path("${UVSR_RUNTIME_SHADER_ROOT}")
if (EXISTS "${UVSR_RUNTIME_SHADER_ROOT}" AND NOT IS_DIRECTORY "${UVSR_RUNTIME_SHADER_ROOT}")
    message(FATAL_ERROR "Runtime shader root is not a directory")
endif()

if (DEFINED UVSR_RUNTIME_SHADER_EXPECTED_COUNT)
    uvsr_read_runtime_shader_inventory("${UVSR_RUNTIME_SHADER_INVENTORY}" package_paths
        "${UVSR_RUNTIME_SHADER_EXPECTED_COUNT}")
else()
    uvsr_read_runtime_shader_inventory("${UVSR_RUNTIME_SHADER_INVENTORY}" package_paths)
endif()
set(framework "${UVSR_FRAMEWORK_SHADER_SOURCE_ROOT}")
set(uvsr "${UVSR_APP_SHADER_SOURCE_ROOT}")
set(sources)
set(relative_paths)
set(expected_keys)
foreach(package_path IN LISTS package_paths)
    string(REGEX MATCH "^bin/shaders/(framework|uvsr)/(.+)$" matched "${package_path}")
    set(source "${${CMAKE_MATCH_1}}/${CMAKE_MATCH_2}")
    string(REGEX REPLACE "^bin/shaders/" "" relative "${package_path}")
    if (NOT EXISTS "${source}" OR IS_DIRECTORY "${source}")
        message(FATAL_ERROR "Compiled runtime shader is missing: ${source}")
    endif()
    uvsr_require_unredirected_shader_path("${source}")
    file(SIZE "${source}" size)
    if (size EQUAL 0)
        message(FATAL_ERROR "Compiled runtime shader is empty: ${source}")
    endif()
    set(destination "${UVSR_RUNTIME_SHADER_ROOT}/${relative}")
    uvsr_require_unredirected_shader_path("${destination}")
    if (IS_DIRECTORY "${destination}")
        message(FATAL_ERROR "Runtime shader destination is a directory: ${destination}")
    endif()
    uvsr_shader_path_key("${relative}" key)
    if (key IN_LIST expected_keys)
        message(FATAL_ERROR "Duplicate runtime shader path: ${relative}")
    endif()
    list(APPEND sources "${source}")
    list(APPEND relative_paths "${relative}")
    list(APPEND expected_keys "${key}")
    get_filename_component(directory "${relative}" DIRECTORY)
    while (directory)
        uvsr_shader_path_key("${directory}" key)
        list(APPEND expected_keys "${key}")
        get_filename_component(directory "${directory}" DIRECTORY)
    endwhile()
endforeach()

file(GLOB_RECURSE entries LIST_DIRECTORIES true RELATIVE "${UVSR_RUNTIME_SHADER_ROOT}"
    "${UVSR_RUNTIME_SHADER_ROOT}/*")
set(retired)
foreach(relative IN LISTS entries)
    set(path "${UVSR_RUNTIME_SHADER_ROOT}/${relative}")
    uvsr_require_unredirected_shader_path("${path}")
    uvsr_shader_path_key("${relative}" key)
    if (NOT key IN_LIST expected_keys)
        list(APPEND retired "${path}")
    endif()
endforeach()

# The canonical inventory and every existing path are proven before mutation.
foreach(source relative IN ZIP_LISTS sources relative_paths)
    set(destination "${UVSR_RUNTIME_SHADER_ROOT}/${relative}")
    get_filename_component(directory "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${source}" "${destination}" ONLY_IF_DIFFERENT)
endforeach()
list(SORT retired ORDER DESCENDING)
foreach(path IN LISTS retired)
    if (IS_DIRECTORY "${path}")
        file(REMOVE_RECURSE "${path}")
    else()
        file(REMOVE "${path}")
    endif()
endforeach()
