include_guard(GLOBAL)

function(uvsr_dependency_path path output)
    if (NOT IS_ABSOLUTE "${path}")
        message(FATAL_ERROR "Dependency path must be absolute: ${path}")
    endif()
    cmake_path(NORMAL_PATH path)
    set(${output} "${path}" PARENT_SCOPE)
endfunction()

function(uvsr_dependency_hash hash output)
    string(TOLOWER "${hash}" hash)
    string(LENGTH "${hash}" length)
    if (NOT length EQUAL 64 OR NOT hash MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "Malformed dependency SHA-256: ${hash}")
    endif()
    set(${output} "${hash}" PARENT_SCOPE)
endfunction()

function(uvsr_verify_dependency_file path expected_hash)
    uvsr_dependency_path("${path}" path)
    uvsr_dependency_hash("${expected_hash}" expected_hash)
    if (NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "Dependency is not a regular file: ${path}")
    endif()
    file(SHA256 "${path}" actual_hash)
    if (NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Dependency SHA-256 mismatch: ${path}")
    endif()
    if (ARGC GREATER 2)
        file(SIZE "${path}" size)
        if (NOT size EQUAL ARGV2)
            message(FATAL_ERROR "Dependency size mismatch: ${path}")
        endif()
    endif()
endfunction()

function(uvsr_verify_dependency_records records expected_count)
    list(LENGTH records count)
    if (NOT expected_count MATCHES "^[1-9][0-9]*$" OR NOT count EQUAL expected_count)
        message(FATAL_ERROR "Dependency record count mismatch: ${count}, expected ${expected_count}")
    endif()
    set(seen)
    foreach(record IN LISTS records)
        string(REPLACE "|" ";" fields "${record}")
        list(LENGTH fields count)
        if (NOT count EQUAL 2)
            message(FATAL_ERROR "Malformed dependency record: ${record}")
        endif()
        list(GET fields 0 path)
        list(GET fields 1 hash)
        uvsr_dependency_path("${path}" path)
        string(TOLOWER "${path}" key)
        if (key IN_LIST seen)
            message(FATAL_ERROR "Duplicate dependency path: ${path}")
        endif()
        list(APPEND seen "${key}")
        uvsr_verify_dependency_file("${path}" "${hash}")
    endforeach()
endfunction()

# Digest sorted UTF-8 records: relative/path|lowercase_sha256\n.
function(uvsr_verify_dependency_tree root expected_count expected_digest)
    uvsr_dependency_path("${root}" root)
    uvsr_dependency_hash("${expected_digest}" expected_digest)
    if (NOT IS_DIRECTORY "${root}" OR IS_SYMLINK "${root}")
        message(FATAL_ERROR "Dependency root is not a directory: ${root}")
    endif()
    set(pattern "*")
    if (ARGC GREATER 3)
        set(pattern "${ARGV3}")
    endif()
    file(GLOB_RECURSE entries LIST_DIRECTORIES true RELATIVE "${root}" "${root}/${pattern}")
    list(SORT entries)
    set(keys)
    set(inventory "")
    foreach(path IN LISTS entries)
        if (path STREQUAL "" OR path MATCHES [[\\|:|(^|/)\.\.?(/|$)|^/|/$|//]] OR
                path MATCHES "[|;\r\n]" OR
                IS_SYMLINK "${root}/${path}")
            message(FATAL_ERROR "Unsafe dependency tree entry: ${root}/${path}")
        endif()
        if (NOT IS_DIRECTORY "${root}/${path}")
            string(TOLOWER "${path}" key)
            if (key IN_LIST keys)
                message(FATAL_ERROR "Duplicate dependency tree path: ${path}")
            endif()
            list(APPEND keys "${key}")
            file(SHA256 "${root}/${path}" hash)
            string(APPEND inventory "${path}|${hash}\n")
        endif()
    endforeach()
    list(LENGTH keys count)
    if (NOT expected_count MATCHES "^[1-9][0-9]*$" OR NOT count EQUAL expected_count)
        message(FATAL_ERROR "Dependency tree count mismatch: ${root}, ${count}, expected ${expected_count}")
    endif()
    string(SHA256 digest "${inventory}")
    if (NOT digest STREQUAL expected_digest)
        message(FATAL_ERROR "Dependency tree digest mismatch: ${root}")
    endif()
endfunction()

function(uvsr_verify_dependency_git source expected_head)
    uvsr_dependency_path("${source}" source)
    uvsr_dependency_path("${GIT_EXECUTABLE}" git)
    if (NOT EXISTS "${git}" OR IS_DIRECTORY "${git}" OR IS_SYMLINK "${git}")
        message(FATAL_ERROR "Git executable is not a regular file: ${git}")
    endif()
    string(TOLOWER "${expected_head}" expected_head)
    string(LENGTH "${expected_head}" length)
    if (NOT length EQUAL 40 OR NOT expected_head MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "Malformed dependency Git revision: ${expected_head}")
    endif()
    execute_process(COMMAND "${git}" -C "${source}" rev-parse --show-toplevel HEAD
        OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    string(REPLACE "\n" ";" revision "${revision}")
    list(LENGTH revision count)
    if (NOT count EQUAL 2)
        message(FATAL_ERROR "Malformed dependency Git identity: ${source}")
    endif()
    list(GET revision 0 root)
    list(GET revision 1 head)
    uvsr_dependency_path("${root}" root)
    string(TOLOWER "${root}" root)
    string(TOLOWER "${source}" key)
    if (NOT root STREQUAL key OR NOT head STREQUAL expected_head)
        message(FATAL_ERROR "Dependency Git identity mismatch: ${source}")
    endif()
    execute_process(COMMAND "${git}" -C "${source}" status --porcelain=v1
            --untracked-files=all --ignore-submodules=none
        OUTPUT_VARIABLE status OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if (NOT status STREQUAL "")
        message(FATAL_ERROR "Dependency Git worktree is not clean: ${source}\n${status}")
    endif()
endfunction()
