cmake_minimum_required(VERSION 3.24)

if (NOT DEFINED UVSR_SOURCE_DIRECTORY)
    get_filename_component(UVSR_SOURCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(manifest "docs/postmortem/publication-manifest.tsv")
set(required_report "docs/postmortem/screen-space-diffuse.md")
if (NOT EXISTS "${UVSR_SOURCE_DIRECTORY}/${manifest}")
    message(FATAL_ERROR "postmortem publication manifest is missing")
endif()

file(STRINGS "${UVSR_SOURCE_DIRECTORY}/${manifest}" rows ENCODING UTF-8)
set(expected "${manifest}")
foreach(row IN LISTS rows)
    if (row MATCHES "^#" OR row STREQUAL "")
        continue()
    endif()
    string(REPLACE "\t" ";" fields "${row}")
    list(LENGTH fields count)
    if (NOT count EQUAL 3)
        message(FATAL_ERROR "postmortem manifest requires hash, path, and source: ${row}")
    endif()
    list(GET fields 0 hash)
    list(GET fields 1 path)
    list(GET fields 2 source)
    string(LENGTH "${hash}" hash_length)
    if (NOT hash_length EQUAL 64 OR NOT hash MATCHES "^[0-9a-f]+$" OR
        NOT path MATCHES "^docs/postmortem/[a-zA-Z0-9_./-]+$" OR
        path MATCHES "(^|/)\\.\\.?(/|$)" OR source STREQUAL "")
        message(FATAL_ERROR "invalid postmortem manifest entry: ${row}")
    endif()
    if (path IN_LIST expected)
        message(FATAL_ERROR "duplicate postmortem manifest path: ${path}")
    endif()
    list(APPEND expected "${path}")
    if (NOT EXISTS "${UVSR_SOURCE_DIRECTORY}/${path}" OR
        IS_DIRECTORY "${UVSR_SOURCE_DIRECTORY}/${path}" OR
        IS_SYMLINK "${UVSR_SOURCE_DIRECTORY}/${path}")
        message(FATAL_ERROR "postmortem is missing or is not a regular file: ${path}")
    endif()
    file(SHA256 "${UVSR_SOURCE_DIRECTORY}/${path}" actual_hash)
    if (NOT actual_hash STREQUAL hash)
        message(FATAL_ERROR
            "postmortem changed; review and update its manifest: ${path}\nSHA-256 ${actual_hash}")
    endif()
endforeach()
if (NOT required_report IN_LIST expected)
    message(FATAL_ERROR "the screen-space diffuse postmortem must be preserved")
endif()
file(GLOB_RECURSE actual LIST_DIRECTORIES false RELATIVE "${UVSR_SOURCE_DIRECTORY}"
    "${UVSR_SOURCE_DIRECTORY}/docs/postmortem/*")
list(SORT actual)
list(SORT expected)
if (NOT actual STREQUAL expected)
    set(unlisted "${actual}")
    list(REMOVE_ITEM unlisted ${expected})
    message(FATAL_ERROR "postmortem files are absent from the manifest: ${unlisted}")
endif()

find_package(Git QUIET)
if (UVSR_REQUIRE_COMMITTED)
    if (NOT GIT_FOUND)
        message(FATAL_ERROR "Git is required to verify postmortem publication readiness")
    endif()
    foreach(path IN LISTS expected)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${UVSR_SOURCE_DIRECTORY}"
            ls-files --error-unmatch -- "${path}" RESULT_VARIABLE tracked
            OUTPUT_QUIET ERROR_QUIET)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${UVSR_SOURCE_DIRECTORY}"
            diff --quiet HEAD -- "${path}" RESULT_VARIABLE changed)
        if (NOT tracked EQUAL 0 OR NOT changed EQUAL 0)
            message(FATAL_ERROR
                "postmortem is not in the exact committed candidate: ${path}; publication remains pending")
        endif()
    endforeach()
endif()

# discover new local reports without copying code or changing any Git state.
if (GIT_FOUND AND NOT UVSR_SKIP_WORKTREE_DISCOVERY)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${UVSR_SOURCE_DIRECTORY}"
        worktree list --porcelain RESULT_VARIABLE listed OUTPUT_VARIABLE worktrees
        ERROR_QUIET)
    if (NOT listed EQUAL 0)
        message(FATAL_ERROR "cannot inspect local worktrees for omitted postmortems")
    endif()
    string(REPLACE "\n" ";" worktree_rows "${worktrees}")
    foreach(row IN LISTS worktree_rows)
        if (NOT row MATCHES "^worktree (.+)$")
            continue()
        endif()
        set(checkout "${CMAKE_MATCH_1}")
        file(GLOB_RECURSE other_reports LIST_DIRECTORIES false RELATIVE "${checkout}"
            "${checkout}/docs/postmortem/*")
        foreach(path IN LISTS other_reports)
            if (NOT path IN_LIST expected)
                message(FATAL_ERROR
                    "unreviewed local postmortem: ${checkout}/${path}; preserve it or record its disposition")
            endif()
        endforeach()
    endforeach()
endif()
list(LENGTH expected total)
if (UVSR_REQUIRE_COMMITTED)
    message(STATUS "postmortems: ${total} files verified in the committed candidate; no upload performed")
else()
    message(STATUS "postmortems: ${total} local files verified; publication requires the committed-candidate check")
endif()
